<a href="https://colab.research.google.com/github/sejallotliker/Numerical_methods_in_python/blob/main/basic_python/python_programming_for_physicists.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Practice problems from Computational Physics by Mark Newman

##Ch-1. Introduction


ENIAC --> 1st computer in human history



In [ ]:
#Python is a powerful programming language. It has many features which makes physics calculations easier and faster.

#Atomic phy problem


# 1/( λ) = R (1/m^2 - 1/n^2)
#Where R : Rydberg constant

# m = 1 --> Lyman
# m = 2 --> Balmer
# m = 3 --> Paschen
# m = 4 --> Bracket
# m = 5 --> P-fund

#Python program that prints out the wavelengths of the first five lines
R = 1.097*10**-2
for m in [1, 2, 3, 4, 5]:
  print("Series for m = ", m )
  for k in [1, 2, 3, 4, 5]:
    n= m+k
    inv_lambda = R*((1/m**2) - (1/n**2))
    print(" ", 1/inv_lambda, "nm")


Series for m =  1
  121.5436037678517 nm
  102.55241567912488 nm
  97.23488301428137 nm
  94.95594044363415 nm
  93.76220862091418 nm
Series for m =  2
  656.3354603463993 nm
  486.1744150714068 nm
  434.084299170899 nm
  410.2096627164995 nm
  397.04243897498225 nm
Series for m =  3
  1875.2441724182836 nm
  1281.9051959890612 nm
  1093.8924339106654 nm
  1005.013673655424 nm
  954.6697605038536 nm
Series for m =  4
  4051.453458928391 nm
  2625.341841385597 nm
  2165.68603077263 nm
  1944.6976602856273 nm
  1817.5443517284903 nm
Series for m =  5
  7458.357503936354 nm
  4652.841081738073 nm
  3739.8031928569753 nm
  3296.3276468290137 nm
  3038.5900941962927 nm


#Ch-2: Python

In [ ]:
x = 1
print(x)

1


In [ ]:
#Variable types ion python
# 1. Integer
x = 1
y = 3
print(x, y)

# 2. Float

x = 1.5
y = 2.5

print (x+y)

# 3. Complex

x = 1+ 2j
y = 5 + 7j

print(x*y)

# 4. String
a = " My name is Sejal"
print(a)

1 3
4.0
(-9+17j)
 My name is Sejal


In [ ]:
#To take input from the user
x = input("Enter the value of x : ")

Enter the value of x : 7


In [ ]:
#Arithmetic

# x + y --> Addition
# x - y --> Subtraction
# x * y --> Multiplication
# x/y --> Division
# x**y --> x raising to the power of y


In [ ]:
#Integer division and modulo operation
# x// y --> Gives the Quotient (integer part)
print(14//3)
print(-14//3)

# x % y --> Modulo (Remainder part)
y = 14%3
print(y)

4
-5
2


In [ ]:
#Python modifiers
## x += 1
## x -= 4
## x*= 2.6
## x/= 5*y
## x//=3.4


In [ ]:
#A ball dropped from a tower
#To print the height above the ground at time tafter it is dropped
h = float(input("Enter the height of the tower in meters: "))
t = float(input("Enter the time interval in sec: "))
g = 9.8
s = (1/2)*g*t**2
height = h-s
print("Height of the tower: ", height)

Enter the height of the tower in meters: 150
Enter the time interval in sec: 2
Height of the tower:  130.4


In [ ]:
#Exercise 2.2: Altitude of a satellite
import math
T = float(input("Enter the time in sec: " ))
def height(T):
  G = 6.67* 10**(-11)
  M = 5.97*10**(24)
  R = 6371*10**2
  pi = math.pi
  h = ((G*M*T**2)/(4*pi**2))**(1/3) - R
  return h
height_1 = height(T)
print(height_1)

Enter the time in sec: 161
2336.4567673050333


In [ ]:
#Math library
from math import log
x = log(2.5)
x

0.9162907318741551

In [ ]:
from math import *
#(* means everything)

In [ ]:
#Converting Polar coordinates
''' x = rcos(theta)
    y = rsin(theta) '''

from math import sin, cos, pi
r = float(input("Enter r: "))

d = float(input("Enter the value of theta in degrees: "))

theta = d*pi/180

x = r*cos(theta)
y = r*sin(theta)

print("x = ", x, "y = ", y)


Enter r: 10
Enter the value of theta in degrees: 20
x =  9.396926207859085 y =  3.420201433256687


In [ ]:
#Inverse operation

x = float(input("Enter the value of x: "))
y = float(input("Enter the value of y: "))

d = (y/x)
r = math.sqrt(x**2+y**2)
theta = math.atan(d)
theta_d = theta*(180/math.pi)

print("r = ", r, "theta= ", theta_d)

Enter the value of x: 10
Enter the value of y: 10000000000000000
r =  1e+16 theta=  89.99999999999994


In [ ]:
#A spaceship travels from Earth in a straight line at a relativistic speed v to another planet x light years away

x = float(input("Enter the value of x : "))
v = float(input("Enter the value of v in the fraction of c : "))

#To print the time in years that the spaceship takes to reach its destination
t = (x/v)
print("Time perceived by a passenger on board is ", t)
t_dialated = (t+(x*v))/math.sqrt(1-(v**2))
print("Time perceived by an observer on the Earth is ", t_dialated)

Enter the value of x : 10
Enter the value of v in the fraction of c : 0.99
Time perceived by a passenger on board is  10.1010101010101
Time perceived by an observer on the Earth is  141.7834014178793


In [ ]:
#Quantum step potential
m = 9.11*10**(-31)
E = 10
V = 9
h_bar = (6.626*10**(-34))/(2*3.14)

k1 = math.sqrt((2*m*E))/h_bar
k2 = math.sqrt(2*m*(E-V))/h_bar

T = (4*k1*k2)/(k1+k2)**2

R = ((k1-k2)/(k1+k2))

print("Transmission coefficient: ", T)
print("Reflection coefficient: ", R)

Transmission coefficient:  0.7301261363877615
Reflection coefficient:  0.5194938532959157


In [ ]:
#Planetary orbits:
#l1--> distance of closest approach perihelon
#v1 --> Velocity at perihelon
#l2 --> distance of farthest approach apihelon
# v2 --> Velocity at apihelon

#Roots : v2
G = 6.6738* 10**(-11)
M = 1.9891*10**(30) #kg
v1 = 3.0287*10**(4) #m/s
l1 = 1.4710*10**(11) #m

a = 1
b = -(2*G*M)/(v1*l1)
c = -(v1**2-((2*G*M)/l1))

v2_1 = (-b + math.sqrt(b**2-4*a*c))/(2*a)
v2_2 = (-b - math.sqrt(b**2-4*a*c))/(2*a)

print("v2 (first root): ", v2_1)
print("v2 (second root): ", v2_2)

v2 (first root):  30287.000000000153
v2 (second root):  29305.399177261148


In [ ]:
#To find all the other parameters of the orbit
#Semi major axis:
l2 = (l1*v1)/v2_2

a = 1/2*(l1+l2)
b = math.sqrt(l1*l2)
T = (2*math.pi*a*b)/(l1*v1)
e = ((l2-l1)/(l2+l1))

T_years = T/(365*24*60*60)

print("Semi major axis: ", a)
print("Semi minor axis: ", b)
print("Orbital period: ", T)
print("Orbital eccentricity: ", e)
print("T in years", T_years)

Semi major axis:  149563598604.3303
Semi minor axis:  149543307136.74207
Orbital period:  31543060.20788706
Orbital eccentricity:  0.016471913134744297
T in years 1.0002238777234609


In [ ]:
#For halley's commet
l1 = 8.7830*10**10 #m
v1 = 5.4529*10**(4) #m/s

#To calculate all the properties again
G = 6.6738* 10**(-11)
M = 1.9891*10**(30) #kg

a = 1
b = -(2*G*M)/(v1*l1)
c = -(v1**2-((2*G*M)/l1))

v2_1 = (-b + math.sqrt(b**2-4*a*c))/(2*a)
v2_2 = (-b - math.sqrt(b**2-4*a*c))/(2*a)

print("v2 (first root): ", v2_1)
print("v2 (second root): ", v2_2)

l2 = (l1*v1)/v2_2

a = 1/2*(l1+l2)
b = math.sqrt(l1*l2)
T = (2*math.pi*a*b)/(l1*v1)
e = ((l2-l1)/(l2+l1))
T_years = T/(365*24*60*60)

print("Semi major axis: ", a)
print("Semi minor axis: ", b)
print("Orbital period: ", T)
print("Orbital eccentricity: ", e)
print("T in years", T_years)

v2 (first root):  54529.0
v2 (second root):  906.6806969191493
Semi major axis:  2685022330438.2207
Semi minor axis:  681129146098.431
Orbital period:  2399312511.8451877
Orbital eccentricity:  0.9672889126454061
T in years 76.08170065465461


In [ ]:
#Therefore we can see that the orbital period of halley's comet is 76 years

In [ ]:
#Controling programs with if else loops
#if statement

x = int(input("Enter a value greater than 10: "))
if x> 10:
  print("Number is greater than 10")
elif x == 10:
  print("Number entered is 10")
else:
    print("Number is less than 10")

Enter a value greater than 10: 10
Number entered is 10


In [ ]:
#Some syntax to remeber
x = 5
if x ==1:
  print(x)

if x> 1:
  print(x)

if x>= 1:
  print(x)

if x< 1:
  print(x)

if x<= 1:
  print(x)

if x!=1:
  print(x)

5
5
5


In [ ]:
#The while statement:
x = int(input("Enter a whole number greater than 10 : "))
while x> 10:
  print("This is greater than 10, please try again")
  x = int(input("Enter a number greater than 10 "))
print("Your number is ", x)


Enter a whole number greater than 10 : 10
Your number is  10


In [ ]:
#break and continue

#Break --> allows us to break out the while loop
#Continue --> Continues the while loop
x = int(input("Enter a number geater than 10 "))
while x>10:
  print("This is greater than 10, please try again")
  x = int(input("Enter a whole number greater than 10"))
  if x == 111:
    break

Enter a number geater than 10 100
This is greater than 10, please try again
Enter a whole number greater than 10111


In [ ]:
#Even and odd numbers
# Remember, n%2 == 0 if and only if n is even
n = int(input("Enter the value of n "))
if n%2 == 0:
  print("Even")
else:
  print("odd")

Enter the value of n 10
Even


In [ ]:
# Program that asks 2 integers --> one even and one odd and keeps asking until it gets what it wants

print("Enter 2 digits, one even and one odd")
m = int(input("Enter the first integer: "))
n = int(input("Enter the second integer: "))
while (m+n)%2 ==0:
  print("One must be even and other odd")
  m = int(input("Enter the first integer: "))
  n = int(input("Enter the second integer: "))
print(f'The numbers you chose are {m} and {n1}')

Enter 2 digits, one even and one odd
Enter the first integer: 5
Enter the second integer: 5
One must be even and other odd
Enter the first integer: 10
Enter the second integer: 10
One must be even and other odd
Enter the first integer: 10
Enter the second integer: 1
The numbers you chose are 10 and 1


In [ ]:
#Example 2.4 : Fibonacci sequence
#Fibonacci sequence is a sequence of integers in which each is the sum of the previous two, with the first 2 numbers being 1 and 1

#1, 1, 2, 3, 5, 8, 13, 21, 34 etc...

f1= 1
f2 =1
while f1<=1000:
  print(f1)
  f_next = f1+f2
  f1= f2
  f2 = f_next

1
1
2
3
5
8
13
21
34
55
89
144
233
377
610
987


In [ ]:
#neater way to solve the same problem: using "multiple assignment" feature
f1, f2 = 1, 1
while f1<= 10000:
  print(f1)
  f1, f2 = f2, f1+f2

1
1
2
3
5
8
13
21
34
55
89
144
233
377
610
987
1597
2584
4181
6765


In [ ]:

#Catalan Numbers
#Catalan numbers are the integers produced as a sequence that plays an imp role in QM

####Using for loop

In [ ]:
# Initialize
c = 1  # C0
n_terms = 10 #Number of terms to compute
c_next = c

# Compute and add next terms
for n in range(1, n_terms):
    c = c * ((4*(n - 1) + 2) / (n + 1)) # Apply recurrence using Cn
    c_next += c
    print(int(c))


1
2
5
14
42
132
429
1430
4862


###Using while loop

In [ ]:
C = 1
n = 0
print(C)

while C <= 1e9:
    C = C*(4*n+2)/(n+2)
    print(int(C))
    n += 1

1
1
2
5
14
42
132
429
1430
4862
16796
58786
208012
742900
2674440
9694845
35357670
129644790
477638700
1767263190


#Lists and array

In [ ]:
#Lists
#It is the most basic type of container in python
# denoted by [ ]
#It can store any kind of data, like integer floats etc...

A = [ 1, 2, 3, 4, 5]
print(A)

[1, 2, 3, 4, 5]


In [ ]:
x = 1
y = 1.5
z = 5.2

r = [x, y, z]
print(r)

[1, 1.5, 5.2]


In [ ]:
from math import sqrt
r = [1, 3.5 ,1.5, 2,5]
length = sqrt(r[0]**2+r[1]**2+r[2]**2+r[3]**2)
print(length)

4.415880433163924


In [ ]:
r[1]

3.5

In [ ]:
len(r)

5

In [ ]:
mean = sum(r)/len(r)
print("mean = ", mean)

mean =  2.6


In [ ]:
#To find the log of the list elements
from math import log
log_r = list(map(log, r))
print(log_r)

[0.0, 1.252762968495368, 0.4054651081081644, 0.6931471805599453, 1.6094379124341003]


In [ ]:
r.append(6.1) #We can add new element to the list

In [ ]:
#To remove an element from a list
r.pop() #It removes the last element
print(r)

#We can remove any number of our choice from the list using r.pop(n) where n --> Number that we wanted to remove

[1, 3.5, 1.5, 2]


In [ ]:
r.pop(2)
print(r)

[1, 3.5, 2]


In [ ]:
#Arrays
#An array is ordered set of values
#Number of elements in an array is fixed
#Can be 2 D or 3D

#Numpy
#Also known as Numerical Python
import numpy as np
a = np.zeros(4, float)
a

array([0., 0., 0., 0.])

In [ ]:
b = np.zeros([3, 4], float)
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
from numpy import empty
a = empty(4, float)

In [ ]:
a = np.array([[2, 3, 4], [7, 8, 9]])
print(a)

[[2 3 4]
 [7 8 9]]


In [1]:
#Slicing in arrays
r = [1, 3, 6, 9, 8, 7, 8, 9, 10]
s = r[2:5]
print(s)

[6, 9, 8]


In [3]:
#Other varients in slicing
a = r[2:]
b = r[:5]
print(a)
print(b)

[6, 9, 8, 7, 8, 9, 10]
[1, 3, 6, 9, 8]


In [4]:
#For loops
r = [1, 3, 5]
for n in r:
  print(n)
  print(2*n)
print("Finished")

1
2
3
6
5
10
Finished


In [5]:
for i in range(5):
  print("Hello Sejal")

Hello Sejal
Hello Sejal
Hello Sejal
Hello Sejal
Hello Sejal


In [9]:
for i in range(50):
  print(i**2)

0
1
4
9
16
25
36
49
64
81
100
121
144
169
196
225
256
289
324
361
400
441
484
529
576
625
676
729
784
841
900
961
1024
1089
1156
1225
1296
1369
1444
1521
1600
1681
1764
1849
1936
2025
2116
2209
2304
2401


In [10]:
#Performing sum
s = 0.0
for k in range(1, 101):
  s+=1/k
print(s)

5.187377517639621


In [17]:
#Exercise-2.9
#Madelung constant
#To write a program to calculate and print the madelung constant for NaCl
import numpy as np
M=0
L = 100
for i in range(-L, L+1):
  for j in range(-L, L+1):
    for k in range(-L, L+1):
      if (i==j==k==0):
        continue
      M += (-1)**(i+j+k)/(np.sqrt(i**2+j**2+k**2))
print(M)

-1.7418198158396654


In [22]:
#Semi empirical mass formula
a1 = 15.8
a2 = 18.3
a3 = 0.714
a4 = 23.2

A = float(input("Enter value of A : "))
Z = float(input("Enter value of Z : "))

if A%2 !=0:
  a5 = 0
elif A%2 ==0 and Z%2 ==0:
  a5 = 12
else:
  a5 = -12
print("a5 = ", a5)

B = a1*A - a2*A**(2/3)- a3*(Z**2/A**(1/3))- a4*(((A-2*Z)**2)/A)+ a5/(A**(1/2))
print("Binding Energy is ", B)

Enter value of A : 58
Enter value of Z : 28
a5 =  12
Binding Energy is  497.5620206224374


In [23]:
#Binding energy per nucleon
B_per_nucleon = B/A
print("Binding energy Per nucleon is ", B_per_nucleon)

Binding energy Per nucleon is  8.578655527973059


In [ ]:
#To find the stable nucleus for A
A = int(input("Enter the value of A "))



In [26]:
#User defined functions
f = 1.0
n = 10
for k in range(1, n+1):
  f*=k
  print(f)

1.0
2.0
6.0
24.0
120.0
720.0
5040.0
40320.0
362880.0
3628800.0


In [30]:
def factorial(n):
  f = 1.0
  for k in range(1, n+1):
    f*=k
  return f

factorial(11)

39916800.0

In [33]:
import numpy as np
def distance(r, theta, z):
  x = r*np.cos(theta)
  y = r*np.sin(theta)
  d = np.sqrt(x**2+y**2+z**2)
  return d

distance(2, 30, 10)

np.float64(10.198039027185569)

In [34]:
#Prime factors and prime number
def factors(n):
  factorlist = []
  k = 2
  while k<=n:
    while n% k ==0:
      factorlist.append(k)
      n//=k
    k+=1
  return factorlist